services:
  fit-friends.server.mongo:
    image: mongo:7.0.9
    restart: always
    container_name: fit-friends-server_mongoDb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - fit-friends_server_data:/data/db

volumes:
  fit-friends_server_data:
