@host = http://localhost:3000
@orderId = 666e0547ef8cac8ac83bd479
@userId = 6669e5a12b10829b5ace1060
@trainingId = 666deb9e10ff48d5830d5607
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjY5ZmEzMDFhNGE0NTdiODA5MmY1OTMiLCJlbWFpbCI6InVzZXIxM0Bub3Rmb3VuZC5sb2NhbCIsIm5hbWUiOiJBQUFBQUEyIiwiaWF0IjoxNzE4MzI1MjE3LCJleHAiOjE3MTg2MjUyMTd9.0bGUe-SCjIzP4dOGeF-37v0oG-BHzBo2MSSmE9OVynreX474iFgheJHVwVoacoRVI9-xTPPGhaojp3KKW7OwOg

### Create a new order
POST {{host}}/api/orders HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user": "{{userId}}",
  "purchase": "абонемент",
  "service": "{{trainingId}}",
  "price": 5000,
  "count": 2,
  "payment": "visa"
}


### Get order by ID
GET {{host}}/api/orders/{{orderId}} HTTP/1.1
Authorization: Bearer {{token}}


### Update order
PATCH {{host}}/api/orders/{{orderId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "count": 4,
  "payment": "umoney"
}


### Delete order by ID
DELETE {{host}}/api/orders/{{orderId}} HTTP/1.1
Authorization: Bearer {{token}}