@host = http://localhost:3000
@orderId = 667e169ca57c257a1dcd5d68
@trainingId = 666deb9e10ff48d5830d5607
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjY5ZmEzMDFhNGE0NTdiODA5MmY1OTMiLCJlbWFpbCI6InVzZXIxM0Bub3Rmb3VuZC5sb2NhbCIsIm5hbWUiOiJBQUFBQUEyIiwiaWF0IjoxNzE5NTMxNTEzLCJleHAiOjE3MjIxMjM1MTN9.yWYfoXoBCBO228IplGH2_FOEkZcLaYv5agWB41pluv5oH3rIdWnatSxRL7v1Dv4KkpVMfWWxJFRQVIdvmT5hRQ

### Create a new order
POST {{host}}/api/orders HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "purchase": "абонемент",
  "service": "{{trainingId}}",
  "price": 5000,
  "count": 2,
  "payment": "visa"
}


### Get order by ID
GET {{host}}/api/orders/{{orderId}} HTTP/1.1
Authorization: Bearer {{token}}


### Update order
PATCH {{host}}/api/orders/{{orderId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "count": 4,
  "payment": "umoney"
}


### Delete order by ID
DELETE {{host}}/api/orders/{{orderId}} HTTP/1.1
Authorization: Bearer {{token}}
