@host = http://localhost:3000
@balanceId = 66807d51e5737344c3e593cb
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmNiNmJmYzI2MTE2N2UyNDZmNzRhOWUiLCJlbWFpbCI6InRlc3Q1QHRlc3QuY29tIiwiaWF0IjoxNzI0OTUwOTkyLCJleHAiOjE3Mjc1NDI5OTJ9.5gjkfcRZ9oAi3_x_UOfT_RZKzw2Xf4qFY6l7KUz6ZLX5aCihmLJW56OncLJHQIRYsKvvqQhaWAPepMeb40vs-w

### Get balance by ID
GET {{host}}/api/balances/{{balanceId}} HTTP/1.1
Authorization: Bearer {{token}}


### Get training purchase
GET {{host}}/api/balances/purchase HTTP/1.1
Authorization: Bearer {{token}}


### Get balances list
GET {{host}}/api/balances HTTP/1.1
Authorization: Bearer {{token}}


### Get active training purchase
GET {{host}}/api/balances/purchase?active=true HTTP/1.1
Authorization: Bearer {{token}}


### Activate purchase
POST {{host}}/api/balances/{{balanceId}} HTTP/1.1
Authorization: Bearer {{token}}


### Deactivate purchase
DELETE {{host}}/api/balances/{{balanceId}} HTTP/1.1
Authorization: Bearer {{token}}
