@host = http://localhost:3000
@balanceId = 66807d51e5737344c3e593cb
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjY5ZmEzMDFhNGE0NTdiODA5MmY1OTMiLCJlbWFpbCI6InVzZXIxM0Bub3Rmb3VuZC5sb2NhbCIsIm5hbWUiOiJBQUFBQUEyIiwiaWF0IjoxNzE5NTMxNTEzLCJleHAiOjE3MjIxMjM1MTN9.yWYfoXoBCBO228IplGH2_FOEkZcLaYv5agWB41pluv5oH3rIdWnatSxRL7v1Dv4KkpVMfWWxJFRQVIdvmT5hRQ

### Get balance by ID
GET {{host}}/api/balances/{{balanceId}} HTTP/1.1
Authorization: Bearer {{token}}

### Get training purchase
GET {{host}}/api/balances/purchase HTTP/1.1
Authorization: Bearer {{token}}

### Get activetraining purchase
GET {{host}}/api/balances/purchase?active=true HTTP/1.1
Authorization: Bearer {{token}}
