@host = http://localhost:3000
@questionnaireId = 666debfe10ff48d5830d5614
@userId = 6669e5a12b10829b5ace1060
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjY5ZmEzMDFhNGE0NTdiODA5MmY1OTMiLCJlbWFpbCI6InVzZXIxM0Bub3Rmb3VuZC5sb2NhbCIsIm5hbWUiOiJBQUFBQUEyIiwiaWF0IjoxNzE4MzI1MjE3LCJleHAiOjE3MTg2MjUyMTd9.0bGUe-SCjIzP4dOGeF-37v0oG-BHzBo2MSSmE9OVynreX474iFgheJHVwVoacoRVI9-xTPPGhaojp3KKW7OwOg

### Create a new questionnaire
POST {{host}}/api/questionnaires HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user": "{{userId}}",
  "skillLevel": "любитель",
  "workout": ["стрейчинг", "аэробика"],
  "workoutDuration": "30-50 мин",
  "caloriesToLose": 5000,
  "dailyCalorieBurn": 2000,
  "isReadyForTraining": true
}


### Get questionnaire by ID
GET {{host}}/api/questionnaires/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}


### Update questionnaire
PATCH {{host}}/api/questionnaires/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "workoutDuration": "50-80 мин",
  "caloriesToLose": 3500
}


### Delete questionnaire by ID
DELETE {{host}}/api/questionnaires/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}