@host = http://localhost:3000
@questionnaireId = 66731044152660a882394c82
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmFkMWJhNzk5YzlkMzYyYmE2MDNjODUiLCJlbWFpbCI6InVzZXIxMzQ1QG5vdGZvdW5kLmxvY2FsIiwiaWF0IjoxNzIyNjIyNzIxLCJleHAiOjE3MjI2MjM2MjF9.AsdYHYMvEPRnTMwTOXdRssk1pWm9ljIAOizZJud92y8tCAB5mQOBSYNwIsqvwqiWg0YrB3tmscCwYUh-zAj4vw

### Create a new questionnaire
POST {{host}}/api/questionnaires/visitor HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "skillLevel": "любитель",
  "workout": ["стрейчинг", "аэробика"],
  "workoutDuration": "30-50 минут",
  "caloriesToLose": 5000,
  "dailyCalorieBurn": 2000,
  "isReadyForTraining": true
}


### Get questionnaire by ID
GET {{host}}/api/questionnaires/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}


### Get last questionnaire by user ID
GET {{host}}/api/questionnaires/latest HTTP/1.1
Authorization: Bearer {{token}}


### Update questionnaire
PATCH {{host}}/api/questionnaires/visitor/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "workoutDuration": "50-80 минут",
  "caloriesToLose": 3500
}


### Delete questionnaire by ID
DELETE {{host}}/api/questionnaires/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}
