@host = http://localhost:3000
@questionnaireId = 66731044152660a882394c82
@userId = 66730db5df58bd000c95a7e0
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjY5ZmEzMDFhNGE0NTdiODA5MmY1OTMiLCJlbWFpbCI6InVzZXIxM0Bub3Rmb3VuZC5sb2NhbCIsIm5hbWUiOiJBQUFBQUEyIiwiaWF0IjoxNzE4NzI4MDUyLCJleHAiOjE3MjEzMjAwNTJ9.Yk6nnS2PYw7DLv2kJ_A1ngU4XIhGh9K8J9a2rMAAp5ZiQNEZWqxJpXsHptqM0JABN1A6ey0oQjEj4MymIwjuHw

### Create a new questionnaire
POST {{host}}/api/questionnaires HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "skillLevel": "любитель",
  "workout": ["стрейчинг", "аэробика"],
  "workoutDuration": "30-50 мин",
  "caloriesToLose": 5000,
  "dailyCalorieBurn": 2000,
  "isReadyForTraining": true
}


### Get questionnaire by ID
GET {{host}}/api/questionnaires/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}


### Get last questionnaire by user ID
GET {{host}}/api/questionnaires/latest HTTP/1.1
Authorization: Bearer {{token}}


### Update questionnaire
PATCH {{host}}/api/questionnaires/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "workoutDuration": "50-80 мин",
  "caloriesToLose": 3500
}


### Delete questionnaire by ID
DELETE {{host}}/api/questionnaires/{{questionnaireId}} HTTP/1.1
Authorization: Bearer {{token}}
