@host = http://localhost:3000
@trainingId = 666de6e37510aa28b5e1a442
@userId = 6669e5a12b10829b5ace1060
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjY5ZmEzMDFhNGE0NTdiODA5MmY1OTMiLCJlbWFpbCI6InVzZXIxM0Bub3Rmb3VuZC5sb2NhbCIsIm5hbWUiOiJBQUFBQUEyIiwiaWF0IjoxNzE5NTMxNTEzLCJleHAiOjE3MjIxMjM1MTN9.yWYfoXoBCBO228IplGH2_FOEkZcLaYv5agWB41pluv5oH3rIdWnatSxRL7v1Dv4KkpVMfWWxJFRQVIdvmT5hRQ

### Create a new training
POST {{host}}/api/trainings HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Morning Yoga",
  "backgroundId": "123e4567-e89b-12d3-a456-426614174001",
  "skillLevel": "любитель",
  "workout": "стрейчинг",
  "workoutDuration": "30-50 минут",
  "price": 3500,
  "caloriesBurned": 3780,
  "description": "A high-intensity interval training session to burn maximum calories",
  "gender": "мужской",
  "videoId": "123e4567-e89b-12d3-a456-426614174001",
  "coach": "{{userId}}",
  "isSpecialOffer": false
}


### Get training by ID
GET {{host}}/api/trainings/{{trainingId}} HTTP/1.1
Authorization: Bearer {{token}}


### Update training
PATCH {{host}}/api/trainings/{{trainingId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "workoutDuration": "50-80 мин",
  "price": 4000
}


### Delete training by ID
DELETE {{host}}/api/trainings/{{trainingId}} HTTP/1.1
Authorization: Bearer {{token}}


### Get trainings
GET {{host}}/api/trainings HTTP/1.1
Authorization: Bearer {{token}}


### Get trainings with filter price and rating
@priceFrom = 1000
@priceTo = 4000
@ratingFrom = 1
@ratingTo = 4
GET {{host}}/api/trainings?priceFrom={{priceFrom}}&priceTo={{priceTo}}&ratingFrom={{ratingFrom}}&ratingTo={{ratingTo}} HTTP/1.1
Authorization: Bearer {{token}}


### Get trainings with filter by free price
@trainingSortType = BY_FREE_PRICE
GET {{host}}/api/trainings?trainingSortType={{trainingSortType}} HTTP/1.1
Authorization: Bearer {{token}}

### Get trainings with sort by price and filter price
@trainingSortType2 = BY_HIGH_PRICE
GET {{host}}/api/trainings?trainingSortType={{trainingSortType2}}&priceFrom={{priceFrom}} HTTP/1.1
Authorization: Bearer {{token}}


### Get special for you training
GET {{host}}/api/trainings/for-you HTTP/1.1
Authorization: Bearer {{token}}
